# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile"]
pygments: true
markdown : rdiscount

permalink: /:year/:title.html

title : Codeurs en Seine
description: "Rencontre de codeurs à Rouen : Agile, Java & Web"
tagline : 
  2013 : "Rencontre de codeurs à Rouen : Agile, Java & Web"
  2014 : "Rencontre de codeurs à Rouen : Web, Agile, Java, Innovation"
date : 
  2013 : "Jeudi 17 octobre 2013"
  2014 : "Jeudi 27 novembre 2014"

production_url : http://www.codeursenseine.com


 
  
