 # This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile",".editorconfig"]
markdown : kramdown

permalink: /meetups/:year-:month-:day/:slug

title : Codeurs en Seine
description: "Rencontre de codeurs à Rouen"
tagline :
  2013 : "Rencontre de codeurs à Rouen : Agile, Java & Web"
  2014 : "Rencontre de codeurs à Rouen : Web, Agile, Java, Innovation"
  2015 : "Rencontre de codeurs à Rouen : Web, Agile, Java, Technologies"
  2016 : "Rencontre de codeurs à Rouen"
  2017 : "Rencontre de codeurs à Rouen"
  meetups : "Retrouvez des rencontres Codeurs en Seine tout au long de l'année !"
  devoxx4kids : "Devoxx 4 Kids Rouen - Atelier de programmation pour les 8-14 ans"
date :
  meetups : "Meetups Codeurs en Seine"
  2013 : "Jeudi 17 octobre 2013"
  2014 : "Jeudi 27 novembre 2014"
  2015 : "Jeudi 26 novembre 2015"
  2016 : "Jeudi 24 novembre 2016<br/>Samedi 26 novembre 2016"
  2017 : "Jeudi 23 novembre 2017"
  devoxx4kids : "Samedi 2 et 9 Décembre 2017 - 14h00-17h30"

production_url : http://www.codeursenseine.com

sass:
  sass_dir: assets/css/
  style: compressed

gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
