# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile"]
highlighter: true
markdown : rdiscount

title : Codeurs en Seine
description: "Rencontre de codeurs à Rouen : Agile, Java & Web"
tagline: "Rencontre de codeurs à Rouen : Agile, Java & Web<br/>Jeudi 27 novembre 2014"

production_url : http://www.codeursenseine.com
